import { motion } from 'framer-motion';
import { Link, NavLink, Route, Routes } from 'react-router-dom';
import { menuSections } from './data/menuData';
import { galleryData } from './data/galleryData';
import { formatPrice } from './utils/formatPrice';
import { useMemo, useState } from 'react';

const wa='https://wa.me/2349168566725';
const Particle=()=> <div className='particles'/>;
const Navbar=()=> <nav className='nav'><Link to='/' className='logo'>SOHO LAGOS</Link><div className='links'>{['/','/menu','/gallery','/reserve'].map((p,i)=><NavLink key={p} to={p}>{['Experience','Menu','Gallery','Reserve'][i]}</NavLink>)}</div><a href='/reserve' className='btn'>Book Now</a></nav>;
const Tilt=({children,className=''})=><motion.div whileHover={{rotateX:4,rotateY:-4,y:-6}} transition={{duration:.3}} className={`tilt ${className}`}>{children}</motion.div>;
const WForm=()=>{const [f,set]=useState({name:'',date:'',time:'',guests:'2',seating:'',occasion:'',request:''}); const url=useMemo(()=>{const t=`Hello SOHO Lagos, I would like to reserve a table.\n\nName: ${f.name}\nDate: ${f.date}\nTime: ${f.time}\nGuests: ${f.guests}\nSeating: ${f.seating}\nOccasion: ${f.occasion}\nSpecial request: ${f.request}\n\nPlease confirm availability.`; return `${wa}?text=${encodeURIComponent(t)}`},[f]); return <div className='card'><div className='quick'>{['2 guests','4 guests','6 guests','Private table'].map(q=><button key={q} onClick={()=>set({...f,guests:q})}>{q}</button>)}</div>{['name','date','time','guests','seating','occasion'].map(k=><input key={k} placeholder={k[0].toUpperCase()+k.slice(1)} value={f[k]} onChange={e=>set({...f,[k]:e.target.value})}/>) }<textarea placeholder='Special request' value={f.request} onChange={e=>set({...f,request:e.target.value})}/><a className='btn w-full' href={url} target='_blank'>Reserve via WhatsApp</a></div>}
const Home=()=> <>
<section className='hero'><div><p className='eyebrow'>SOHO LAGOS</p><h1>Inspired dining, quietly elevated.</h1><p>Asian fusion, refined atmosphere, and long, unhurried evenings in Lekki Phase 1.</p><div className='row'><Link className='btn' to='/reserve'>Reserve a Table</Link><Link className='btn ghost' to='/menu'>View Menu</Link></div></div><Tilt className='hero3d'><div className='ring3d'/></Tilt></section>
<section className='grid3'>{['The Room','The Plate','The Night'].map((t,i)=><Tilt key={t}><h3>{t}</h3><p>{['Warm light, dark textures, and a setting made for unhurried evenings.','Asian influence, modern Lagos energy, and dishes composed with intention.','A refined transition from dinner to conversation, cocktails, and atmosphere.'][i]}</p></Tilt>)}</section>
<section><h2>Composed plates. Quiet confidence.</h2><div className='grid4'>{menuSections.slice(0,2).flatMap(s=>s.items).slice(0,4).map(i=><Tilt key={i.name}><p>{i.name}</p><small>{i.subtitle||''}</small><span>{formatPrice(i.price)}</span></Tilt>)}</div></section>
<section><h2>Every angle should feel like a reservation.</h2><div className='strip'>{galleryData.map(g=><img key={g.id} src={g.image} loading='lazy' alt={g.title}/>)}</div></section>
<section><h2>Your table, curated before you arrive.</h2><WForm/></section>
</>;
const Menu=()=>{const [q,set]=useState(''); return <section><p className='eyebrow'>THE MENU</p><h1>A quieter expression of appetite.</h1><input className='search' placeholder='Search menu' value={q} onChange={e=>set(e.target.value)}/>{menuSections.map(s=><div key={s.category}><h3>{s.category}</h3>{s.items.filter(i=>i.name.toLowerCase().includes(q.toLowerCase())).map(i=><div className='item' key={i.name}><div><strong>{i.name}</strong><p>{i.description}</p></div><span>{formatPrice(i.price)}</span></div>)}</div>)}<a className='btn' href={wa}>Reserve via WhatsApp</a></section>}
const Gallery=()=>{const [f,set]=useState('All'); const [m,setM]=useState(null); const arr=f==='All'?galleryData:galleryData.filter(i=>i.category===f); return <section><h1>Gallery</h1><p>A study in warm light, composed plates, and the theatre of a room made for staying longer.</p><div className='row'>{['All','Interior','Plates','Cocktails','Evenings'].map(c=><button key={c} className='chip' onClick={()=>set(c)}>{c}</button>)}</div><div className='masonry'>{arr.map(i=><Tilt key={i.id}><img src={i.image} loading='lazy' alt={i.title} onClick={()=>setM(i)}/></Tilt>)}</div>{m&&<div className='lightbox' onClick={()=>setM(null)}><img src={m.image} alt={m.title}/></div>}</section>}
const Reserve=()=> <section><h1>Reserve the evening.</h1><p>Choose your time, share the details, and confirm directly through WhatsApp.</p><WForm/><p>6A Ogbunike Street, Lekki Phase 1, Lagos, Nigeria · 10am – 12am daily · Smart casual</p></section>
export default function App(){return <div className='app'><Particle/><Navbar/><Routes><Route path='/' element={<Home/>}/><Route path='/menu' element={<Menu/>}/><Route path='/gallery' element={<Gallery/>}/><Route path='/reserve' element={<Reserve/>}/></Routes><footer>SOHO LAGOS · RSVP: 09168566725 · <a href='https://www.instagram.com/soho.lagos/'>Instagram</a></footer>{/* Replace placeholder visuals with licensed SOHO visuals before client delivery. */}</div>}
